# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
      exclude: "^examples|^test"
    - id: end-of-file-fixer
      exclude: "^examples|^test"
    - id: check-yaml
      # Can't check source yaml since it has go templates in it.
      exclude: ^charts/.*/templates/
      args: [ --allow-multiple-documents ]
    - id: check-added-large-files
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
    - id: helmlint
