{{- if .Values.synthetics.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-synthetics-runner.secretName" . }}
  labels:
    {{- include "splunk-synthetics-runner.labels" . | nindent 4 }}
type: Opaque
data:
  runner_token: {{ .Values.synthetics.secret.runnerToken | b64enc | quote }}
{{- end -}}
